# Fichier de configuration

[ror]
# First order for ror
1 = [ 5, 2, 0, 12, 10, 7, 11, 4, 1, 3, 6, 9, 8 ]
# Second order for ror
2 = [ 9, 2, 3, 11, 6, 1, 12, 7, 8, 4, 5, 10, 0 ]

[order]
# Order default
1 = [ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f' ]

[disorder]
# First list for replace
1 = [ '9', '1', '#', 'h', '4', '5', 'm', '@', '8', '(', '&', 'b', '3', 'a', 'Z', 'f' ]
# Second list for replace
2 = [ '=', 'X', '7', '>', '$', '0', '"', 'J', '1', '+', '.', 'S', ']', '*', 'q', '!' ]
